sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4.0"
  - "5.0"

env:
  - "FAKEREDIS=true  ACTIONDOMAINS=true"
  - "FAKEREDIS=true  ACTIONDOMAINS=false"
  - "FAKEREDIS=false ACTIONDOMAINS=true"
  - "FAKEREDIS=false ACTIONDOMAINS=false"

os:
  - linux
  # - osx
  # - windows

script: npm run-script test-travis

services:
  - redis-server

before_script:
  - npm install -g grunt-cli

after_script:
  - npm run-script coverage

after_failure:
  - "cat /home/travis/builds/evantahler/actionhero/npm-debug.log"

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/0b77e5af8eb07ea0ea0c'
    on_success: always
    on_failure: always
    on_start:   true
